### PR TITLE
Conf file should be name application.conf, was applications.conf

### PR DESCRIPTION
**Pull request by byrnedo**
Wasn't actually loading the conf as far as I could see.

### CODE REVIEW

**Comment by jacobus** [comment]
Thanks

**Comment by byrnedo** [comment]
No worries, awesome template project by the way :)

**Comment by jacobus** [comment]
Thanks Donal,

I'll try to branch the project within the next week or two for a Akka-HTTP
with Slick 3 version. Just lazy ;-) and busy. But it's about time.

Cheers,
Jacobus

**Comment by byrnedo** [comment]
Ah great!! Wasn't aware of the Akka Http stuff, from looking around it's 
still experimental is it? or is it hitting stable soon? Never too early :)

**Comment by jacobus** [comment]
Spray became part of Typesafe a while ago and is now integrated into Akka
as Akka-HTTP. The Spray directives and routing DSL will still make you feel
at home, but it's built on top of Akka Streams, so there are some
fundamental differences.

Have a look at these great tutorials:

https://github.com/theiterators/akka-http-microservice
https://github.com/theiterators/reactive-microservices
https://github.com/hseeberger/reactive-flows

**Comment by byrnedo** [comment]
I had a quick look, looks quite interesting, a lot to get my head around :)

**Pull request merged**
